### ISSUE TITLE
Consider adding Typescript typings

### ISSUE THREAD

**Issue by Sebazzz** [Anstinus/lazy-linq#2]
In my opinion LINQ works best with a strong-typed programming model. Consider adding typescript bindings. You may be able to adapt Typescript bindings from similar projects which have ported LINQ.

**Comment by jeswin** [comment]
@Sebazzz Ask and you shall receive. https://github.com/Anstinus/lazy-linq/pull/5
Please review if you get time.

**Comment by Sebazzz** [comment]
LGTM - also appears to support NoImplicitAny.
